services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: always

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge